### ISSUE TITLE
Detail stylesheet doesn't account for figures

### ISSUE THREAD

**Issue by tpritc** [brentsimmons/NetNewsWire#959]
First things first, I love the new NetNewsWire! Thank you for all the hard work that went into creating it.

I've run into an issue where the images in certain articles are absolutely massive. I've noticed this most of all on The Points Guy. Check out [this article](https://thepointsguy.com/guide/5-actionable-ways-to-deal-with-the-post-summer-vacation-blues/) in NetNewsWire 5.0 to see what I mean.

I've attached a screen recording of that article in the current release:

![ezgif com-optimize](https://user-images.githubusercontent.com/1939143/64241218-2a1a7180-cefb-11e9-8484-28ca0cb79f1f.gif)

I've dug into the html and it looks like we're just not forcing `figure`s to use the same styles as we are `img`s and `video`s in the detail stylesheet ([link to the line](https://github.com/brentsimmons/NetNewsWire/blob/fa5840811adffdb9f390d35634f8db29631dfba0/Mac/MainWindow/Detail/styleSheet.css#L125)).

It's a quick fix. I've got it working nicely in my local development build by using:

```css
img, figure, video {
	max-width: 100%;
	height: auto;
	margin: 0 auto;
}

figcaption {
	font-size: 14px;
	padding: 0;
}
```

I'll whip up a quick PR to sort it out.
